services:
  - type: web
    name: 1wxxv
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn app:create_app()
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
